name: Discord Release Notes

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  release-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notes to Discord
        uses: alienindisgui-se/discord-changelog-notifier@main
        with:
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
          language: 'sv'  # Empty for English, 'sv' for Swedish